# Site info
name: RJ226
tagline: Helping YOU build better in Minecraft
description: RJ226 helps you become a great builder in Minecraft using some of things that I have learnt from my time playing Minecraft and from watching others.
author: RJ226
logo: /ms-icon-310x310.png
lang: en_GB

# Social SEO profiles, following and sharing
social:
  name: RJ226
  links:
    - https://www.youtube.com/channel/UC3J585n81BMItgouCZOZi_w
    - https://twitter.com/226Rj
    - https://www.reddit.com/r/RJ226/
    - https://discord.gg/cBUVsja
  share-links:
    twitter: true
    facebook: true
    pinterest: true
    reddit: true
    email: true

# Web analytics
analytics:
  gtag: "UA-174966777-1"  # Fill in your Google Analytics gtag.js ID to track your website using gtag
  #google_analytics: ""   # Fill in your Google Analytics ID to track your website using GA
  #gtm: ""                # Google Tag Manager ID

# Outputting
baseurl: ""
timezone: Europe/London
permalink: /:categories/:title

# Site config
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Front Matter defaults
defaults:
  -
    scope:
      path: ""
      type: ""
    values:
      layout: default
  -
    scope:
      path: _posts/playlists
      type: posts
    values:
      layout: playlist
      category: playlists
      social-share: true
      playlist:
        type: Playlist
        channel: RJ226
